language: node_js
node_js:
  - '8'

notifications:
  email:
    recipients:
      - enfarious@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
    
notifications:
  slack:
    rooms:
      - splicedinfinities:jqNfekoqH3jXS8xJBFGe8UGN#general
